{
  config,
  lib,
  pkgs,
  ...
}:
let
  # Raw hex colors (no `#` prefix) for Hyprland's `rgb(...)` syntax.
  c = config.theme.colors;
  theme = config.theme.colorsHex;

  pb = pkg: bin: "${pkg}/bin/${bin}";
  # Convenience: absolute store paths for everything we exec from Hyprland so
  # the compositor never depends on PATH.
  g = pb pkgs.ghostty "ghostty";
  wk = pb pkgs.walker "walker";
  mc = pb pkgs.mako "makoctl";
  lock = pb pkgs.hyprlock "hyprlock";
  idle = pb pkgs.hypridle "hypridle";
  hs = pb pkgs.hyprsunset "hyprsunset";
  picker = pb pkgs.hyprpicker "hyprpicker";
  osd = pb pkgs.swayosd "swayosd-client";
  osdService = pb pkgs.swayosd "swayosd-server";
  bg = pb pkgs.swaybg "swaybg";
  grim = pb pkgs.grim "grim";
  slurp = pb pkgs.slurp "slurp";
  copy = pb pkgs.wl-clipboard "wl-copy";
  bright = pb pkgs.brightnessctl "brightnessctl";
  player = pb pkgs.playerctl "playerctl";
  chrome = pb pkgs.chromium "chromium";
  files = pb pkgs.nautilus "nautilus";
  obsidian = pb pkgs.obsidian "obsidian";
  signal = pb pkgs.signal-desktop "signal-desktop";
  bar = pb pkgs.waybar "waybar";
  power = pb pkgs.wlogout "wlogout";
  btop = pb pkgs.btop "btop";
  nm = pb pkgs.networkmanagerapplet "nm-applet";
  blm = pb pkgs.blueman "blueman-applet";
  polkit = "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1";
  wallpaper = "${config.home.homeDirectory}/.config/hypr/wallpaper.png";

  # ---------------------------------------------------------------------------
  # The Hyprland 0.55 Lua config. hyprlang is deprecated as of 0.55, and Home
  # Manager's own Lua translator emits legacy hyphenated names
  # (`hl.exec-once`, `hl.bezier`, `hl.windowrulev2`) that are invalid Lua and
  # abort Hyprland at startup. So we author the canonical `hl.*` config here.
  # ---------------------------------------------------------------------------
  hyprlandLua = ''
    -- auto-generated by home/chriswrendev/hyprland.nix

    hl.config({
      general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 2,
        col = {
          active_border = { colors = {"rgb(${c.accent})", "rgb(${c.color4})"}, angle = 45 },
          inactive_border = "rgb(${c.color8})",
        },
        layout = "dwindle",
        allow_tearing = false,
        resize_on_border = false,
      },

      decoration = {
        rounding = 0,
        blur = {
          enabled = true,
          size = 2,
          passes = 2,
          special = true,
          brightness = 0.60,
          contrast = 0.75,
        },
        shadow = {
          enabled = true,
          range = 2,
          render_power = 3,
          color = "rgba(1a1a1aee)",
        },
      },

      dwindle = {
        preserve_split = true,
        force_split = 2,
      },

      master = {
        new_status = "master",
      },

      input = {
        kb_layout = "gb",
        kb_options = "compose:caps",
        follow_mouse = 1,
        numlock_by_default = true,
        sensitivity = 0,
        touchpad = {
          natural_scroll = false,
          clickfinger_behavior = true,
          scroll_factor = 0.4,
        },
      },

      misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        disable_scale_notification = true,
        focus_on_activate = true,
        anr_missed_pings = 3,
        on_focus_under_fullscreen = 1,
        force_default_wallpaper = 0,
        allow_session_lock_restore = true,
      },

      cursor = {
        hide_on_key_press = true,
        warp_on_change_workspace = 1,
      },

      binds = {
        hide_special_on_workspace_change = true,
      },

      ecosystem = {
        no_update_news = true,
      },

      xwayland = {
        enabled = true,
        force_zero_scaling = true,
      },
    })

    -- Curves and animations (Omarchy's defaults)
    hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
    hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
    hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
    hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1.0}   } })
    hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}      } })

    hl.animation({ leaf = "global",          enabled = true, speed = 10,   bezier = "default" })
    hl.animation({ leaf = "border",          enabled = true, speed = 5.39, bezier = "easeOutQuint" })
    hl.animation({ leaf = "windows",         enabled = true, speed = 3.79, bezier = "easeOutQuint" })
    hl.animation({ leaf = "windowsIn",       enabled = true, speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
    hl.animation({ leaf = "windowsOut",      enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
    hl.animation({ leaf = "fadeIn",          enabled = true, speed = 1.73, bezier = "almostLinear" })
    hl.animation({ leaf = "fadeOut",         enabled = true, speed = 1.46, bezier = "almostLinear" })
    hl.animation({ leaf = "fade",            enabled = true, speed = 3.03, bezier = "quick" })
    hl.animation({ leaf = "layers",          enabled = true, speed = 3.81, bezier = "easeOutQuint" })
    hl.animation({ leaf = "layersIn",        enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
    hl.animation({ leaf = "layersOut",       enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
    hl.animation({ leaf = "fadeLayersIn",    enabled = true, speed = 1.79, bezier = "almostLinear" })
    hl.animation({ leaf = "fadeLayersOut",   enabled = true, speed = 1.39, bezier = "almostLinear" })
    hl.animation({ leaf = "workspaces",      enabled = false })

    -- Environment (Wayland-first, matching Omarchy)
    hl.env("XCURSOR_SIZE", "24")
    hl.env("HYPRCURSOR_SIZE", "24")
    hl.env("GDK_BACKEND", "wayland,x11,*")
    hl.env("QT_QPA_PLATFORM", "wayland;xcb")
    hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
    hl.env("MOZ_ENABLE_WAYLAND", "1")
    hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
    hl.env("OZONE_PLATFORM", "wayland")
    hl.env("XDG_SESSION_TYPE", "wayland")
    hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
    hl.env("XDG_SESSION_DESKTOP", "Hyprland")
    hl.env("XCOMPOSEFILE", "~/.XCompose")

    -- Autostart (matching Omarchy's session services). Also starts the
    -- `hyprland-session.target` / `graphical-session.target` chain that Home
    -- Manager's systemd units (walker, elephant, ...) are bound to. We start
    -- the importer first so the user environment is available.
    hl.on("hyprland.start", function()
      hl.exec_cmd("systemctl --user import-environment $(env | cut -d'=' -f 1)")
      hl.exec_cmd("dbus-update-activation-environment --systemd --all")
      hl.exec_cmd("systemctl --user start hyprland-session.target")
      hl.exec_cmd("${idle}")
      hl.exec_cmd("${pkgs.mako}/bin/mako")
      hl.exec_cmd("${bar}")
      hl.exec_cmd("${bg} -m fill -i ${wallpaper}")
      hl.exec_cmd("${osdService}")
      hl.exec_cmd("${polkit}")
      hl.exec_cmd("${nm} --indicator")
      hl.exec_cmd("${blm}")
    end)

    -- Window rules (Omarchy's app-tweaks, translated to the 0.55 `hl.window_rule` API)
    hl.window_rule({ name = "suppress-maximize-events", match = { class = ".*" }, suppress_event = "maximize" })
    hl.window_rule({ name = "fix-xwayland-drags", match = {
        class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false,
      }, no_focus = true })
    hl.window_rule({ name = "float-pavucontrol", match = { class = "^(pavucontrol)$" }, float = true })
    hl.window_rule({ name = "float-blueman",     match = { class = "^(blueman)$" },     float = true })
    hl.window_rule({ name = "float-nm-applet",   match = { class = "^(nm-applet)$" },   float = true })
    hl.window_rule({ name = "float-calculator",  match = { class = "^(gnome-calculator)$" }, float = true })
    hl.window_rule({ name = "float-imv",         match = { class = "^(imv)$" },         float = true })
    hl.window_rule({ name = "float-pip",         match = { title = "^(Picture-in-Picture)$" }, float = true })
    hl.window_rule({ name = "float-open-file",   match = { title = "^(Open File)$" },   float = true })
    hl.window_rule({ name = "float-save-as",     match = { title = "^(Save As)$" },     float = true })
    hl.window_rule({ name = "float-confirm",     match = { title = "^(Confirm)$" },     float = true })
    hl.window_rule({ name = "terminal-scroll",   match = { class = "(ghostty|wezterm)" }, scroll_touchpad = 1.5 })

    -- Unified clipboard: SUPER + C/V/X work everywhere, including terminals
    -- (CTRL+Insert / SHIFT+Insert are the universal copy/paste shortcuts).
    hl.bind("SUPER + C", hl.dsp.send_shortcut({ mods = "CTRL", key = "Insert" }))
    hl.bind("SUPER + V", hl.dsp.send_shortcut({ mods = "SHIFT", key = "Insert" }))
    hl.bind("SUPER + X", hl.dsp.send_shortcut({ mods = "CTRL", key = "X" }))
  '';

  # Keybindings kept in a separate Nix list for readability; joined below.
  keybinds = ''
    -- Applications
    hl.bind("SUPER + Return",          hl.dsp.exec_cmd("${g}"))
    hl.bind("SUPER + SHIFT + Return",  hl.dsp.exec_cmd("${g} -e tmux new-session -s Work"))
    hl.bind("SUPER + SHIFT + B",       hl.dsp.exec_cmd("${chrome}"))
    hl.bind("SUPER + SHIFT + N",       hl.dsp.exec_cmd("${g} -e nvim ."))
    hl.bind("SUPER + SHIFT + F",       hl.dsp.exec_cmd("${files} --new-window"))
    hl.bind("SUPER + SHIFT + D",       hl.dsp.exec_cmd("${g} -e lazydocker"))
    hl.bind("SUPER + SHIFT + G",       hl.dsp.exec_cmd("${signal}"))
    hl.bind("SUPER + SHIFT + O",       hl.dsp.exec_cmd("${obsidian}"))

    -- Window management
    hl.bind("SUPER + W",               hl.dsp.window.close())
    hl.bind("SUPER + T",               hl.dsp.window.float({ action = "toggle" }))
    hl.bind("SUPER + F",               hl.dsp.window.fullscreen({ mode = "fullscreen" }))
    hl.bind("SUPER + CTRL + F",        hl.dsp.window.fullscreen({ mode = "maximized" }))
    hl.bind("SUPER + ALT + F",         hl.dsp.window.fullscreen({ mode = "maximized" }))
    hl.bind("SUPER + J",               hl.dsp.layout("togglesplit"))
    hl.bind("SUPER + P",               hl.dsp.window.pseudo())
    hl.bind("SUPER + O",               hl.dsp.window.pin())
    hl.bind("SUPER + S",               hl.dsp.workspace.toggle_special("scratchpad"))
    hl.bind("SUPER + SHIFT + S",       hl.dsp.window.move({ workspace = "special:scratchpad" }))

    -- Focus
    hl.bind("SUPER + left",            hl.dsp.focus({ direction = "left" }))
    hl.bind("SUPER + right",           hl.dsp.focus({ direction = "right" }))
    hl.bind("SUPER + up",              hl.dsp.focus({ direction = "up" }))
    hl.bind("SUPER + down",            hl.dsp.focus({ direction = "down" }))
    hl.bind("SUPER + H",               hl.dsp.focus({ direction = "left" }))
    hl.bind("SUPER + L",               hl.dsp.focus({ direction = "right" }))
    hl.bind("SUPER + K",               hl.dsp.focus({ direction = "up" }))
    hl.bind("SUPER + J",               hl.dsp.focus({ direction = "down" }))

    -- Swap
    hl.bind("SUPER + SHIFT + left",    hl.dsp.window.swap({ direction = "left" }))
    hl.bind("SUPER + SHIFT + right",   hl.dsp.window.swap({ direction = "right" }))
    hl.bind("SUPER + SHIFT + up",      hl.dsp.window.swap({ direction = "up" }))
    hl.bind("SUPER + SHIFT + down",    hl.dsp.window.swap({ direction = "down" }))

    -- Workspaces
    hl.bind("SUPER + 1",               hl.dsp.focus({ workspace = 1 }))
    hl.bind("SUPER + 2",               hl.dsp.focus({ workspace = 2 }))
    hl.bind("SUPER + 3",               hl.dsp.focus({ workspace = 3 }))
    hl.bind("SUPER + 4",               hl.dsp.focus({ workspace = 4 }))
    hl.bind("SUPER + 5",               hl.dsp.focus({ workspace = 5 }))
    hl.bind("SUPER + 6",               hl.dsp.focus({ workspace = 6 }))
    hl.bind("SUPER + 7",               hl.dsp.focus({ workspace = 7 }))
    hl.bind("SUPER + 8",               hl.dsp.focus({ workspace = 8 }))
    hl.bind("SUPER + 9",               hl.dsp.focus({ workspace = 9 }))
    hl.bind("SUPER + 0",               hl.dsp.focus({ workspace = 10 }))

    hl.bind("SUPER + SHIFT + 1",       hl.dsp.window.move({ workspace = 1 }))
    hl.bind("SUPER + SHIFT + 2",       hl.dsp.window.move({ workspace = 2 }))
    hl.bind("SUPER + SHIFT + 3",       hl.dsp.window.move({ workspace = 3 }))
    hl.bind("SUPER + SHIFT + 4",       hl.dsp.window.move({ workspace = 4 }))
    hl.bind("SUPER + SHIFT + 5",       hl.dsp.window.move({ workspace = 5 }))
    hl.bind("SUPER + SHIFT + 6",       hl.dsp.window.move({ workspace = 6 }))
    hl.bind("SUPER + SHIFT + 7",       hl.dsp.window.move({ workspace = 7 }))
    hl.bind("SUPER + SHIFT + 8",       hl.dsp.window.move({ workspace = 8 }))
    hl.bind("SUPER + SHIFT + 9",       hl.dsp.window.move({ workspace = 9 }))
    hl.bind("SUPER + SHIFT + 0",       hl.dsp.window.move({ workspace = 10 }))

    -- Workspace navigation
    hl.bind("SUPER + Tab",             hl.dsp.focus({ workspace = "e+1" }))
    hl.bind("SUPER + SHIFT + Tab",     hl.dsp.focus({ workspace = "e-1" }))
    hl.bind("SUPER + CTRL + Tab",      hl.dsp.focus({ workspace = "previous" }))

    -- Move workspace to a monitor
    hl.bind("SUPER + SHIFT + ALT + left",  hl.dsp.workspace.move({ monitor = "left" }))
    hl.bind("SUPER + SHIFT + ALT + right", hl.dsp.workspace.move({ monitor = "right" }))
    hl.bind("SUPER + SHIFT + ALT + up",    hl.dsp.workspace.move({ monitor = "up" }))
    hl.bind("SUPER + SHIFT + ALT + down",  hl.dsp.workspace.move({ monitor = "down" }))

    -- Groups (as in Omarchy)
    hl.bind("SUPER + G",               hl.dsp.group.toggle())
    hl.bind("SUPER + ALT + G",         hl.dsp.window.move({ out_of_group = true }))
    hl.bind("SUPER + ALT + Tab",       hl.dsp.group.next())
    hl.bind("SUPER + ALT + SHIFT + Tab", hl.dsp.group.prev())
    hl.bind("SUPER + CTRL + left",     hl.dsp.group.prev())
    hl.bind("SUPER + CTRL + right",    hl.dsp.group.next())
    hl.bind("SUPER + ALT + left",      hl.dsp.window.move({ into_group = "left" }))
    hl.bind("SUPER + ALT + right",     hl.dsp.window.move({ into_group = "right" }))
    hl.bind("SUPER + ALT + up",        hl.dsp.window.move({ into_group = "up" }))
    hl.bind("SUPER + ALT + down",      hl.dsp.window.move({ into_group = "down" }))

    -- Screenshots
    hl.bind("Print",                   hl.dsp.exec_cmd("${grim} -g \"$(${slurp})\" - | ${copy}"))
    hl.bind("SUPER + Print",           hl.dsp.exec_cmd("${grim} - | ${copy}"))

    -- Clipboard history
    hl.bind("SUPER + CTRL + V",        hl.dsp.exec_cmd("${wk} -m clipboard"))

    -- Launcher & utilities
    hl.bind("SUPER + Space",           hl.dsp.exec_cmd("${wk}"))
    hl.bind("SUPER + ALT + Space",     hl.dsp.exec_cmd("${wk}"))
    hl.bind("SUPER + Escape",          hl.dsp.exec_cmd("${power} -b 3 -T 500 -B 500"))
    hl.bind("SUPER + CTRL + E",        hl.dsp.exec_cmd("${wk} -m symbols"))

    -- System
    hl.bind("SUPER + CTRL + L",        hl.dsp.exec_cmd("${lock}"))
    hl.bind("SUPER + SHIFT + Space",   hl.dsp.exec_cmd("pkill waybar || ${bar}"))
    hl.bind("SUPER + SHIFT + C",       hl.dsp.exec_cmd("${picker} -a"))

    -- Notifications (mako)
    hl.bind("SUPER + Comma",           hl.dsp.exec_cmd("${mc} dismiss"))
    hl.bind("SUPER + SHIFT + Comma",   hl.dsp.exec_cmd("${mc} dismiss --all"))
    hl.bind("SUPER + ALT + Comma",     hl.dsp.exec_cmd("${mc} invoke"))
    hl.bind("SUPER + SHIFT + ALT + Comma", hl.dsp.exec_cmd("${mc} restore"))

    -- Toggles
    hl.bind("SUPER + CTRL + I",        hl.dsp.exec_cmd("pgrep -x hypridle >/dev/null && pkill hypridle || ${idle}"))
    hl.bind("SUPER + CTRL + N",        hl.dsp.exec_cmd("pgrep -x hyprsunset >/dev/null && pkill hyprsunset || ${hs} -t 4000"))
    hl.bind("SUPER + CTRL + T",        hl.dsp.exec_cmd("${g} -e btop"))

    -- Media / brightness (SwayOSD feedback)
    hl.bind("XF86AudioRaiseVolume",   hl.dsp.exec_cmd("${osd} --output-volume raise"),       { locked = true, repeating = true })
    hl.bind("XF86AudioLowerVolume",   hl.dsp.exec_cmd("${osd} --output-volume lower"),       { locked = true, repeating = true })
    hl.bind("XF86AudioMute",          hl.dsp.exec_cmd("${osd} --output-volume mute-toggle"), { locked = true })
    hl.bind("XF86AudioMicMute",       hl.dsp.exec_cmd("${osd} --input-volume mute-toggle"),  { locked = true })
    hl.bind("XF86MonBrightnessUp",    hl.dsp.exec_cmd("${bright} set 5%+"),                  { locked = true, repeating = true })
    hl.bind("XF86MonBrightnessDown",  hl.dsp.exec_cmd("${bright} set 5%-"),                  { locked = true, repeating = true })
    hl.bind("SHIFT + XF86MonBrightnessUp",   hl.dsp.exec_cmd("${bright} set 100%"),          { locked = true })
    hl.bind("SHIFT + XF86MonBrightnessDown", hl.dsp.exec_cmd("${bright} set 1%"),            { locked = true })
    hl.bind("ALT + XF86AudioRaiseVolume", hl.dsp.exec_cmd("${osd} --output-volume +1"),      { locked = true, repeating = true })
    hl.bind("ALT + XF86AudioLowerVolume", hl.dsp.exec_cmd("${osd} --output-volume -1"),      { locked = true, repeating = true })
    hl.bind("ALT + XF86MonBrightnessUp",   hl.dsp.exec_cmd("${bright} set 1%+"),             { locked = true, repeating = true })
    hl.bind("ALT + XF86MonBrightnessDown", hl.dsp.exec_cmd("${bright} set 1%-"),             { locked = true, repeating = true })
    hl.bind("XF86AudioPlay",          hl.dsp.exec_cmd("${player} play-pause"),               { locked = true })
    hl.bind("XF86AudioNext",          hl.dsp.exec_cmd("${player} next"),                     { locked = true })
    hl.bind("XF86AudioPrev",          hl.dsp.exec_cmd("${player} previous"),                 { locked = true })

    -- Mouse
    hl.bind("SUPER + mouse_down",     hl.dsp.focus({ workspace = "e+1" }))
    hl.bind("SUPER + mouse_up",       hl.dsp.focus({ workspace = "e-1" }))
    hl.bind("SUPER + mouse:272",      hl.dsp.window.drag(),    { mouse = true })
    hl.bind("SUPER + mouse:273",      hl.dsp.window.resize(),  { mouse = true })
  '';
in
{
  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;

    # We author the Hyprland 0.55 Lua config directly below (HM's own Lua
    # translator emits legacy hyphenated function names like `hl.exec-once`
    # which are invalid Lua and abort Hyprland at startup). Keep HM's translator
    # in "hyprlang" mode so it writes an (unused) hyprland.conf instead of a
    # broken hyprland.lua; our hyprland.lua below is what Hyprland loads,
    # because Hyprland prefers hyprland.lua over hyprland.conf when both exist.
    #
    # `settings` holds a single harmless entry purely so HM's "you enabled
    # systemd but have no settings" warning is silenced. The hyprland.conf HM
    # writes from it is never loaded (we use hyprland.lua).
    configType = "hyprlang";
    settings.misc.disable_hyprland_logo = true;
  };

  # The canonical Hyprland 0.55 Lua config (hyprlang is deprecated in 0.55).
  xdg.configFile."hypr/hyprland.lua".text = hyprlandLua + keybinds;

  # --------------------------------------------------------------------------
  # XCompose file for emoji and special characters (as in Omarchy)
  # --------------------------------------------------------------------------
  home.file.".XCompose".text = ''
    include "%L"

    # Emoji
    <Multi_key> <m> <s> : "😄" # smile
    <Multi_key> <m> <c> : "😂" # cry
    <Multi_key> <m> <l> : "😍" # love
    <Multi_key> <m> <v> : "✌️"  # victory
    <Multi_key> <m> <h> : "❤️"  # heart
    <Multi_key> <m> <y> : "👍" # yes
    <Multi_key> <m> <n> : "👎" # no
    <Multi_key> <m> <f> : "🖕" # fuck
    <Multi_key> <m> <w> : "🤞" # wish
    <Multi_key> <m> <r> : "🤘" # rock
    <Multi_key> <m> <k> : "😘" # kiss
    <Multi_key> <m> <e> : "🙄" # eyeroll
    <Multi_key> <m> <d> : "🤤" # droll
    <Multi_key> <m> <m> : "💰" # money
    <Multi_key> <m> <x> : "🎉" # xellebrate
    <Multi_key> <m> <1> : "💯" # 100%
    <Multi_key> <m> <t> : "🥂" # toast
    <Multi_key> <m> <p> : "🙏" # pray
    <Multi_key> <m> <i> : "😉" # wink
    <Multi_key> <m> <o> : "👌" # OK
    <Multi_key> <m> <g> : "👋" # greeting
    <Multi_key> <m> <a> : "💪" # arm
    <Multi_key> <m> <b> : "🤯" # blowing

    # Typography
    <Multi_key> <space> <space> : "—"
  '';

  # Wallpaper (copied from the Omarchy Tokyo Night theme)
  home.file.".config/hypr/wallpaper.png".source = ../../wallpapers/tokyo-night.jpg;

  # Screen share picker CSS
  xdg.configFile."hypr/hyprland-preview-share-picker.css".text = ''
    @define-color foreground #${theme.foreground};
    @define-color background #${theme.background};
    @define-color accent #${theme.accent};
    @define-color muted #${theme.color8};
    @define-color card_bg #${theme.color0};
    @define-color text_dark #${theme.background};
    @define-color accent_hover #${theme.color12};
    @define-color selected_tab #${theme.accent};
    @define-color text #${theme.foreground};

    * {
      all: unset;
      font-family: JetBrains Mono NF;
      color: @foreground;
      font-weight: bold;
      font-size: 16px;
    }

    .window {
      background: alpha(@background, 0.95);
      border: solid 2px @accent;
      margin: 4px;
      padding: 18px;
    }

    tabs {
        padding: 0.5rem 1rem;
    }

    tabs > tab {
        margin-right: 1rem;
    }

    .tab-label {
        color: @text;
        transition: all 0.2s ease;
    }

    tabs > tab:checked > .tab-label, tabs > tab:active > .tab-label {
        text-decoration: underline currentColor;
        color: @selected_tab;
    }

    tabs > tab:focus > .tab-label {
        color: @foreground;
    }

    .page {
        padding: 1rem;
    }

    .image-label {
        font-size: 12px;
        padding: 0.25rem;
    }

    flowboxchild > .card, button > .card {
        transition: all 0.2s ease;
        border: solid 2px transparent;
        border-color: @background;
        border-radius: 5px;
        background-color: @card_bg;
        padding: 5px;
    }

    flowboxchild:hover > .card, button:hover > .card, flowboxchild:active > .card, flowboxchild:selected > .card, button:active > .card, button:selected > .card, button:focus > .card {
        border: solid 2px @accent;
    }

    .image {
        border-radius: 5px;
    }

    .region-button {
        padding: 0.5rem 1rem;
        border-radius: 5px;
        background-color: @accent;
        color: @text_dark;
        transition: all 0.2s ease;
    }

    .region-button > label {
        color: @text_dark;
    }

    .region-button:not(:disabled):hover, .region-button:not(:disabled):focus {
        background-color: @accent_hover;
        color: @text_dark;
    }

    .region-button:disabled {
        background-color: @muted;
        color: @background;
    }
  '';
}
